### ISSUE TITLE
[Docs] README improvements

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-images/images#1539]
In an effort to improve images documentation, the Developer Enablement team has performed an audit to identify READMEs that are incomplete or missing important information on how to use an image. We also identified a series of image variants that do not include a dedicated README.

This issue is relevant because the image READMEs are used to generate [documentation](https://edu.chainguard.dev/chainguard/chainguard-images/reference), and without proper instructions a user may not know how to use an image in practice.

This is a parent issue to facilitate tracking what is being updated. Individual issues will be created soon_ish_.

The following list contains images that we identified as having READMES that need an update, and/or having variants that are not documented at all. There are more, but these seem like higher priorities at the moment:

```[tasklist]
### Tasks
- [ ] https://github.com/chainguard-images/images/issues/1541
- [ ] https://github.com/chainguard-images/images/issues/1542
- [ ] https://github.com/chainguard-images/images/issues/1543
- [ ] https://github.com/chainguard-images/images/issues/1544
- [ ] https://github.com/chainguard-images/images/issues/1545
- [ ] https://github.com/chainguard-images/images/issues/1546
- [ ] https://github.com/chainguard-images/images/issues/1547
- [ ] https://github.com/chainguard-images/images/issues/1548
- [ ] https://github.com/chainguard-images/images/issues/1549
- [ ] https://github.com/chainguard-images/images/issues/1550
- [ ] https://github.com/chainguard-images/images/issues/1551
```

Watch this issue for individual tasks that we'll be tagging for Hacktoberfest.
/cc @ltagliaferri @jamonation @amouat @SharpRake .

**Comment by gnewson** [comment]
Hi, I'd like to have a go at one or more of these.  Is there a README that you would suggest could be used as a reference  of what a good README looks like, e.g. structure and content.
Thanks.

**Comment by ltagliaferri** [comment]
Welcome @gnewson ! The [PHP readme](https://github.com/chainguard-images/images/tree/main/images/php#readme) is the gold standard. If you haven't seen Erika's [dev.to post](https://dev.to/chainguard/get-involved-with-chainguard-projects-for-hacktoberfest-2023-4h7b), there's more info there too. Thank you for your help and feel free to tag me in your PRs.

**Comment by gnewson** [comment]
Perfect.  Many thanks.  I'll take a look at both.

**Comment by jamonation** [comment]
For images with multiple variants (I think we might call them components now?), I made a PR over in https://github.com/chainguard-dev/images-autodocs/pull/4 that parses an image's annotations to derive the readme file for all the images.

It seems to correctly find the cert-manager, spire, and calico readme for the collections of images. Kyverno has an empty readme.

So for those sets of images, the correct file to edit will be:
1. calico: [images/calico/README.md](https://github.com/chainguard-images/images/blob/main/images/calico/README.md)
2. cert-manager: [images/cert-manager/README.md](https://github.com/chainguard-images/images/blob/main/images/cert-manager/README.md)
3. kyverno: [images/kyverno/README.md](https://github.com/chainguard-images/images/blob/main/images/kyverno/README.md)
4. spire: [images/spire/README.md](https://github.com/chainguard-images/images/blob/main/images/spire/README.md)
